export const CHANGE_USERNAME = "CHANGE_USERNAME";
export const ADD_REPO = "ADD_REPO";

export const REQUEST_REPOS_PENDING = "REQUEST_REPOS_PENDING";
export const REQUEST_REPOS_SUCCESS = "REQUEST_REPOS_SUCCESS";
export const REQUEST_REPOS_FAILED = "REQUEST_REPOS_FAILED";

export const REQUEST_README_PENDING = "REQUEST_README_PENDING";
export const REQUEST_README_SUCCESS = "REQUEST_README_SUCCESS";
export const REQUEST_README_FAILED = "REQUEST_README_FAILED";
